### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by RizzooTv** [moped-scripts/moped_doctor#1]
A way to say that the doctor only work when there is no (real doctor online) would be mega good.

Maybe that would be possible :)

**Comment by totsu0jv** [comment]
I'll have a look at it soon! 😃

**Comment by totsu0jv** [comment]
Done ! 😄 https://github.com/moped-scripts/moped_doctor/commit/3c25c1779d1d61ef0e7228df417e287d19c60dfe
