### ISSUE TITLE
job query

### ISSUE THREAD

**Issue by RizzooTv** [moped-scripts/moped_doctor#2]
Currently you can only add ONE job that is queried, would be cool if you can enter several, in my case I would have to query 4 if someone is online.

thanks for your work

**Comment by DerHobbs** [comment]
> 

Yes, that wouldn't be bad, that's true.

**Comment by totsu0jv** [comment]
Done! I didn't test this tho so please report any bugs! Thanks. 😄 ee08edf161ee738ba8fcc843baf0f2e8c712abcc
